# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('hapdb_rcpp_hello_world', PACKAGE = 'hapdb')
}

rcpp_uncompress_bitpack_haplotypes <- function(rawData, N) {
    .Call('hapdb_rcpp_uncompress_bitpack_haplotypes', PACKAGE = 'hapdb', rawData, N)
}

