import os.path
import glob
#import UnitTest

def configure( conf ):
	pass

def create_test( bld, name ):
	bld(
		features = 'cxx cprogram',
		target = name,
		source = [  'test/' + name + '.cpp' ],
		uselib_local = 'snptest',
		includes='./include',
		unit_test=1,
		install_path = None
	)

def create_benchmark( bld, name ):
	bld(
		features = 'cxx cprogram',
		target = name,
		source = [  'benchmarks/' + name + '.cpp' ],
		uselib_local = 'snptest',
		includes='./include',
		install_path = None
	)


def build( bld ):
	import Options
	
	#---------------------
	# libs
	#---------------------
	bld(
		features = 'cxx cstaticlib',
		target = 'snptest',
		source = bld.glob( 'src/*.cpp' ),
		includes='./include',
		uselib_local='fputils eigen',
		uselib = 'BOOST',
		export_incdirs = './include'
	)
	
	create_test( bld, 'test_snptest2_null_model' )
	create_test( bld, 'test_snptest2_alternative_model' )
