import os.path
import glob
#import UnitTest

def configure( conf ):
	pass

def create_tests( bld, name ):
	bld(
		features = 'cxx cprogram',
		target = name,
		source = bld.glob( 'test/*.cpp' ),
		uselib_local = 'snptest',
		uselib = 'BOOST_UNIT_TEST_FRAMEWORK',
		includes='./include',
		unit_test=1,
		install_path = None
	)

def create_benchmark( bld, name ):
	bld(
		features = 'cxx cprogram',
		target = name,
		source = [  'benchmarks/' + name + '.cpp' ],
		uselib_local = 'snptest',
		includes='./include',
		install_path = None
	)


def build( bld ):
	import Options
	
	#---------------------
	# libs
	#---------------------
	bld(
		features = 'cxx cstaticlib',
		target = 'snptest',
		source = bld.glob( 'src/*.cpp' ) + bld.glob( 'src/case_control/*.cpp' ),
		includes='./include',
		uselib_local='fputils eigen genfile integration',
		uselib = 'BOOST',
		export_incdirs = './include'
	)
	
	create_tests( bld, 'test_snptest' )
