def build( bld ):
	subdirs = [ 'CallComparerComponent', 'HaplotypeFrequencyComponent', 'SNPSummaryComponent', 'RelatednessComponent', 'SampleSummaryComponent' ]
        for subdir in subdirs:
                bld.add_subdirs( subdir )

