def build( bld ):
	subdirs = [ 'HaplotypeFrequencyComponent', 'SNPSummaryComponent', 'RelatednessComponent', 'SampleSummaryComponent', 'SNPOutputComponent' ]
	for subdir in subdirs:
		bld.add_subdirs( subdir )

