import os.path
import glob
#import UnitTest

def configure( conf ):
	pass

def build( bld ):
	import Options
	
	#---------------------
	# libs
	#---------------------
	bld(
		features = 'cxx cstaticlib',
		target = 'worker',
		source = [
			'src/Worker.cpp',
			'src/SynchronousWorker.cpp',
			'src/MultiThreadedWorker.cpp',
			'src/QueuedMultiThreadedWorker.cpp'
		],
		includes='./include',
		uselib = 'BOOST BOOST_THREAD',
		export_includes = './include'	
	)
	
	bld(
		features = 'cxx cprogram',
		target = 'test_worker',
		source = bld.path.ant_glob 'test/*.cpp' ),
		includes='./include',
		uselib_local = 'worker',
		uselib = 'BOOST BOOST_UNIT_TEST_FRAMEWORK',
		unit_test = 1,
		install_path = None
	)
