import os.path
import glob
#import UnitTest

def configure( conf ):
	pass

def build( bld ):
	bld.stlib(
		target = 'statfile',
		source = bld.path.ant_glob( 'src/*.cpp' ),
		includes='./include ../genfile/include',
		use = 'genfile BOOST BOOST_IOSTREAMS ZLIB',
		export_includes = './include'
	)
	
	bld.program(
		target = 'test_statfile',
		source = bld.path.ant_glob( 'test/*.cpp' ),
		use = 'statfile boost_unit_test_framework BOOST_IOSTREAMS ZLIB BOOST_UNIT_TEST_FRAMEWORK',
		includes='./include',
		unit_test=1,
		install_path=None
	)
